//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldredBrown.ProFootball.AspNet.MvcWebApp.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueSeason
    {
        public string LeagueName { get; set; }
        public int SeasonID { get; set; }
        public double TotalGames { get; set; }
        public double TotalPoints { get; set; }
        public Nullable<double> AveragePoints { get; set; }
    
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
    }
}
